### ISSUE TITLE
How to integrate localazer in existing react-webpack project?

### ISSUE THREAD

**Issue by Ajwah** [AlexSergey/rockpack#11]
Following instructions at: https://github.com/AlexSergey/rockpack/blob/master/packages/localazer/README.md
when running `node makePOT.js`, I get the error:

```
src/index.js: Support for the experimental syntax 'jsx' isn't currently enabled (22:3):

  20 |
  21 | ReactDOM.render(
> 22 |   <React.StrictMode>
     |   ^
  23 |     <App />
  24 |   </React.StrictMode>,
  25 |   document.getElementById('root')

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
✨  Done in 3.71s.
```

This pertains t an existing `create-react-app` project in which I did `yarn eject`.

**Comment by AlexSergey** [comment]
Thank you for your attention to the project! It will be possible really soon on Rockpack 2.0. I will update readmes and articles for this case.
