### ISSUE TITLE
Can't set custom hash class name

### ISSUE THREAD

**Issue by keyofevergreen** [AlexSergey/rockpack#30]
Hello. I don't understand how to set up Webpack with FrontendCompiler. I want to make hash classes look more readable in browser.
Please tell me what's wrong.
My config:

```
frontendCompiler({
  styles: 'styles.css',
  vendor: ['react', 'react-dom'],
  html: {
    template: path.resolve(__dirname, './index.ejs'),
    favicon: path.resolve(__dirname, './favicon.ico')
  },
}, (finalConfig) => {
  finalConfig.loader = {
    test: /\.scss$/,
    use: [
      require.resolve('style-loader'),
      {
        loader: require.resolve('css-loader'),
        options: {
          importLoaders: 1,
          modules: true,
          localIdentName: "[name]__[local]___[hash:base64:5]"
        },
      },
    ],
  }
});
```

**Comment by AlexSergey** [comment]
Hello, @keyofevergreen ! Thank you for using Rockpack! Your question is little bit tricky, because modules and plugins are overriding in finalConfig. In this case, we need to modify it directly:

```js
frontendCompiler({
  styles: 'styles.css',
  vendor: ['react', 'react-dom'],
  html: {
    template: path.resolve(__dirname, './index.ejs'),
    favicon: path.resolve(__dirname, './favicon.ico')
  },
}, (config, modules, plugins) => {
  const { use } = modules.get('scssModules')[0];
  const cssLoader = use[1];
  cssLoader.options.modules = {
    localIdentName: "ROCKPACK_[name]__[local]___[hash:base64:5]"
  }
});
```

You also can see [Advanced Example](https://github.com/AlexSergey/rockpack/tree/master/packages/compiler/examples/advanced-config-elm-support) how to modify webpack config.

**Comment by keyofevergreen** [comment]
Thanks for the help! There is one more question. Can I ask it here or create a separate issue?

**Comment by AlexSergey** [comment]
> Thanks for the help! There is one more question. Can I ask it here or create a separate issue?

Ask here, please

**Comment by keyofevergreen** [comment]
The application does not deploy correctly to gh-pages: 
`Failed to load resource: the server responded with a status of 404 ()`

This is fixed if dots are added to `index.ejs` before `<%- css or js %>` in `<link href="<%- css or js %>" >`.
Like this:

```
<html lang="en">
<head>
   ...
</head>
<body>
<div id="root"></div>
<% if (Array.isArray(htmlWebpackPlugin.files.css)) { %>
    <% htmlWebpackPlugin.files.css.forEach(function(css){ %>
        <link rel="preload" href=".<%- css %>" as="style">
        <link href=".<%- css %>" rel="stylesheet">
    <% }); %>
<% } %>
<% if (Array.isArray(htmlWebpackPlugin.files.js)) { %>
    <% htmlWebpackPlugin.files.js.forEach(function(js){ %>
        <script src=".<%- js %>" type="text/javascript"></script>
    <% }); %>
<% } %>
</body>
</html>
```

But if you leave it like this and work with the develompent version, then `Failed to load resource: the server responded with a status of 404 ()` error will occur after any change in the application code. 

Used [this](https://github.com/rafgraph/spa-github-pages) guide for deploying a SPA application.

So, I'm not sure I found the right solution about point substitutions, although it works ..

**Comment by AlexSergey** [comment]
> ```js
> frontendCompiler({
>   styles: 'styles.css',
>   vendor: ['react', 'react-dom'],
>   html: {
>     template: path.resolve(__dirname, './index.ejs'),
>     favicon: path.resolve(__dirname, './favicon.ico')
>   },
> }, (config, modules, plugins) => {
>   const { use } = modules.get('scssModules')[0];
>   const cssLoader = use[1];
>   cssLoader.options.modules = {
>     localIdentName: "ROCKPACK_[name]__[local]___[hash:base64:5]"
>   }
> });
> ```

You can try use something like this:

```js
frontendCompiler({
  styles: 'styles.css',
  vendor: ['react', 'react-dom'],
  html: {
    template: path.resolve(__dirname, './index.ejs'),
    favicon: path.resolve(__dirname, './favicon.ico')
  },
}, (config, modules, plugins) => {
  if (process.env.NODE_ENV === 'production') {
    finalConfig.output.publicPath = './';
  }
});
```

**Comment by keyofevergreen** [comment]
Thanks :)
