### ISSUE TITLE
How to execute application with HTTPS protocol

### ISSUE THREAD

**Issue by bkbalaind** [AlexSergey/rockpack#7]
It's good question. We have some application with auth0. Auth0 don't like use http protocol and suggest to use https.
I looked documentation about this inside @rockpack/compiler, but i didn't found it.

Thanks

**Comment by AlexSergey** [comment]
Hi! Thank you for your question. You can override compiled config if you use callback function like this:

```js
const { backendCompiler } = require('@rockpack/compiler');

backendCompiler(options, webpackConfig => {
  Object.assign(finalConfig.devServer, {
    https: {
      key: fs.readFileSync('/path/to/server.key'),
      cert: fs.readFileSync('/path/to/server.crt'),
      ca: fs.readFileSync('/path/to/ca.pem'),
    }
  });
});
```

More details about https' webpack support you can find [here](https://webpack.js.org/configuration/dev-server/)
